export enum TokenType {
	BADGE = "Badge",
	CAPTION = "Caption",
	CODE_INLINE = "CodeInline",
	CODE_BLOCK = "CodeBlock",
	CODE_IN_CODE = "CodeInCode",
	COLOR = "Color",
	DOCUMENT = "Document",
	IMAGE = "Image",
	HEADING_FIRST = "HeadingFirst",
	HEADING_SECOND = "HeadingSecond",
	HEADING_THIRD = "HeadingThird",
	HEADING_FORTH = "HeadingForth",
	HEADING_FIFTH = "HeadingFifth",
	HEADING = "Heading",
	LINK = "Link",
	LIST = "List",
	PARAGRAPH_START = "ParagraphStart",
	PARAGRAPH_END = "ParagraphEnd",
	PARAGRAPH = "Paragraph",
	QUOTE = "Quote",
	STRONG = "Strong",
	TEXT = "Text",
	UNDER_LINE = "UnderLine",
	UNKNOWN_TEXT = "UnknownText",
	UNMARKABLE = "Unmarkable"
	
}